import { dirname } from 'path'
import { fileURLToPath } from 'url'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
})

const eslintConfig = [
  // Ignore patterns (replaces .eslintignore)
  {
    ignores: [
      'scripts/',
      '.next/',
      'out/',
      'node_modules/',
      'dist/',
      'build/',
      'coverage/',
      '**/*.mdx', // Ignore MDX files to prevent parsing errors with Tailwind classes
      '**/*.cjs', // Ignore CommonJS files (legitimately use require())
      'next-env.d.ts', // Auto-generated by Next.js, should not be linted
      'tailwind.config.ts', // Tailwind requires synchronous require() for plugins
    ],
  },

  // Extend Next.js configs
  ...compat.extends('next/core-web-vitals', 'next/typescript', 'prettier'), // Global rules
  {
    rules: {
      // Accessibility rules for better SEO and UX
      '@next/next/no-img-element': 'error',
      '@next/next/no-html-link-for-pages': 'error',

      // TypeScript rules - warnings instead of errors for now
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',

      // React Hooks rules - downgraded to warnings (Phase 10: fix and re-enable as errors)
      // See VALIDATE-ANALYSIS.md for details on 113 errors introduced by react-hooks@7.0.1
      // Using 'warn' keeps technical debt visible while unblocking the build
      'react-hooks/error-boundaries': 'warn', // TODO: Fix JSX in try/catch blocks
      'react-hooks/set-state-in-effect': 'warn', // TODO: Fix table-of-contents.tsx
      'react-hooks/refs': 'warn', // TODO: Fix button.tsx ref handling

      // Atomic Design enforcement - prevent imports from non-standard component folders
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '@/components/!(atoms|molecules|organisms|templates|analytics|links|seo|ui)/*',
              ],
              message:
                'Import from Atomic Design hierarchy (atoms/molecules/organisms/templates) or approved domain folders (analytics/links/seo/ui) only.',
            },
            {
              group: ['@/components/engagement/*', '@/components/podcast/*'],
              message:
                'These folders have been migrated. Use @/components/organisms or @/components/molecules instead.',
            },
          ],
        },
      ],
    },
  }, // MDX-specific overrides
  {
    files: ['**/*.mdx'],
    ...compat.extends('plugin:mdx/recommended')[0],
    rules: {
      // Relax some rules for MDX files
      '@next/next/no-img-element': 'off',
    },
  },
]

export default eslintConfig
